### ISSUE TITLE
Erro Upgrate MB_5.3.3

### ISSUE THREAD

**Issue by rfminelli** [magnusbilling/mbilling#1]
Ao tentar fazer upgrade do sistema com o comando:
/var/www/html/mbilling/protected/commands/update.sh

O  mesmo executa o procedimento e retorna erro ao final:
=======================WWW.MAGNUSBILLING.COM==========================
_      _                               ______ _ _ _ _
|\    /|                               | ___ (_) | (_)
| \  / | ___  ____ _ __  _   _   _____ | |_/ /_| | |_ _ __   __ _
|  \/  |/   \/  _ \| '_ \| | | \| ___| | ___ \ | | | | '_ \ /  _ \
| |\/| |  | |  (_| | | | | |_| ||____  | |_/ / | | | | | | |  (_| |
|_|  |_|\___|\___  |_| | |_____|_____|  \___/|_|_|_|_|_| |_|\___  |
                _/ |                                           _/ |
               |__/                                           |__/

============================== UPDATE =================================

--2017-04-05 09:24:38--  http://master.dl.sourceforge.net/project/magnusbilling/MBilling-5-current.tar.gz
Resolvendo master.dl.sourceforge.net (master.dl.sourceforge.net)... 216.34.181.56
Conectando-se a master.dl.sourceforge.net (master.dl.sourceforge.net)|216.34.181.56|:80... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 28232588 (27M) [application/x-gzip]
Salvando em: “MBilling-5-current.tar.gz”

100%[=====================================================================>] 28.232.588   235KB/s   em 1m 59s

2017-04-05 09:26:38 (231 KB/s) - “MBilling-5-current.tar.gz” salvo [28232588/28232588]

5.3.3mkdir: é impossível criar o diretório “/var/www/tmpmagnus”: Arquivo existe

**Comment by magnussolution** [comment]
ola, nao é um erro, é somente informando que o diretório ja existe.

**Comment by rfminelli** [comment]
Sim eu sei, mas pois aqui para que possa ser corrigido o script para não mais apresentar a mensagem.

**Comment by rfminelli** [comment]
Correção para não mais exibir a msg.
File: /var/www/html/mbilling/protected/commands/update.sh

Substituir a linha 42
mkdir /var/www/tmpmagnus

Por essas
if [ ! -d "/var/www/tmpmagnus" ]; then
mkdir /var/www/tmpmagnus
fi
