### ISSUE TITLE
Problemas no Billing do DID

### ISSUE THREAD

**Issue by yurikurka** [magnusbilling/mbilling#3]
Detectei um problema na interrupção do DID caso nao tenha Saldo em conta!

Mesmo o Billing  sendo efetuado corretamente na cobrança de ligações entrantes no DID,  o DID continua e recendo ligações mesmo o cliente estando com a conta negativa ou zerado. Conclusão é efetuado a cobrança porem o DID continua recebendo ligações com ou sem saldo no cliente,  e os serviços não são interrompidos!

**Comment by magnussolution** [comment]
Este problema sera solucionado na versão 6 do MagnusBilling. A versão pre-release ja foi publicada.
