### ISSUE TITLE
Número não encontrado.

### ISSUE THREAD

**Issue by jeanpassos** [magnusbilling/mbilling#4]
Quando disca para um número a mensagem de número não pode ser encontrado.

No console apresenta:

Connected to Asterisk 14.6.0 currently running on telefonia-backup (pid = 727)
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Using SIP RTP CoS mark 5
    -- Executing [32233098@billing:1] AGI("SIP/1000-0000001d", ""/var/www/html/m                                                 billing/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php":
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:Jean
 "/var/www/html/mbilling/agi.php": 554832233098
       > "/var/www/html/mbilling/agi.php": USERNAME=Jean DESTINATION=55483223309                                                 8 PLAN=1 CREDIT=5.0000
    -- "/var/www/html/mbilling/agi.php": The number 554832233098, no exist in th                                                 e plan 1
    -- "/var/www/html/mbilling/agi.php": prepaid-dest-unreachable
       > 0x7fbba8fccf90 -- Probation passed - setting RTP source address to 179.                                                 223.144.103:5921
    -- <SIP/1000-0000001d> Playing 'prepaid-dest-unreachable.gsm' (escape_digits                                                 =#) (sample_offset 0) (language 'br')
    -- <SIP/1000-0000001d>AGI Script /var/www/html/mbilling/agi.php completed, r                                                 eturning 4
  == Spawn extension (billing, 32233098, 1) exited non-zero on 'SIP/1000-0000001                                                 d'

**Comment by magnussolution** [comment]
Ola, pela versão do Asterisk que esta ao no seu LOG, vc deve estar testando  o MagnusBilling 6. Neste caso, coloque o problema no repositório correto. 

https://github.com/magnussolution/magnusbilling6/issues

Att.
